services:
  - type: web
    name: pengstrike-multiplayer
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
